apiVersion: batch/v1
kind: Job
metadata:
  name: prepare-dns
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation #HookSucceeded
spec:
  template:
    spec:
      containers:
        - name: init
          image: busybox
          command: ["sh", "-c", "echo preparing DNS..."]
      restartPolicy: Never
