apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: busybox-test-cf
  namespace: argocd
spec:
  destination:
    namespace: cert-manager
    server: https://k3d-target-server-0:6443
#    server: https://kubernetes.default.svc
  source:
    repoURL: registry-1.docker.io/alkon100
    chart: busybox-test-chart
    targetRevision: v1.0.1
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true